### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lukeeey** [DragonetMC/DragonProxy#132]
Just a few things to keep track of. Feel free to edit and add more.

---

Directory Refactor :
  - [x] Move everything inside the root `proxy` folder to the root
  - [x] Move everything outside of `org/dragonet/proxy` folder in [org/dragonet](https://github.com/DragonetMC/DragonProxy/tree/master/proxy/src/main/java/org/dragonet) into the `org/dragonet/proxy` folder
- [x] Split into modules

Entities :
  - [ ] Fix boat entities
  - [ ] Fix entities metadatas (need to know data values) #147 
  - [x] Fix missing entities  
  - [ ] Implement Entities properties
  - [ ] Implement other containers
  - [ ] Implement hit animation

Player :
  - [x] Fix inventory / chest management #155 
  - [ ] Implement creative inventory
  - [x] Implement creative middle click, block pick (probably need a chunk cache)
  - [x] Fix health update #123 
  - [x] Fix Y 0 bug #84 
  - [ ] Implement boss bar
  - [x] Fix translated chat messages #130 
  - [x] Handle disconnect from downstream
  - [ ] Fix movement on slabs/half-blocks #164

World :
  - [x] Fix block entities
  - [x] Fix block data values #147 
  - [ ] Implement block break animation
  - [ ] Implement sounds

Bonus :
  - [x] Add commit hash in version, auto update version from pom
  - [x] Feature : Minecraft authentication in form #131 
  - [x] Feature : Skins Java to Bedrock and Bedrock to Java
  - [x] Feature : Control forms via plugin messages
  - [ ] Feature : Resource packs
  - [ ] Fix RakNet server shutdown #158 
  - [ ] Properly implement Minecraft loopback exemption so users can join servers on the same machine
  - [ ] Add CLSv2 integration
 
Feel free to create an issue with the point you want to talk about or work on.

**Comment by HoverEpic** [comment]
I'll take a look at this, this is a mojor dirrectory change and can't be quickly =)

**Comment by lukeeey** [comment]
It can be done very quickly with a PC. I'm the one that made the change when playing with maven modules but it messed up since i tried to make the modules depend on each other. Just move everything out of the proxy directory to the root, and make sure to overwrite the root pom.

**Comment by HoverEpic** [comment]
Please wait the next merge of indev =)

**Comment by mikroskeem** [comment]
Why not use Gradle though?

**Comment by HoverEpic** [comment]
Personally, i have a better knowledge of maven and my ide does not support fully gradle =P, so i prefer maven for projects.

**Comment by lukeeey** [comment]
I think we all prefer maven so we use maven

**Comment by DefinitlyEvil** [comment]
I don't like gradle either, maven FTW!

**Comment by HoverEpic** [comment]
@lukeeey https://github.com/DragonetMC/DragonProxy/commit/0c74358c913d5ba910bf86a09aa95eb3ceb16259
I have cleand all the mess in coding style and comments (not all my fault).
I haven't made all files, i'll do them when i'll see problems.

**Comment by HoverEpic** [comment]
Done and merged.
