### ISSUE TITLE
Long list of issues

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#17]
The 0.15.4 update has been released a while ago and we have updated DragonProxy to allow clients to join.

However, im sure many bugs still remain. Please comment bugs and i will add them to this list.

---
### Bugs
- [ ] PE players cant walk up stairs (#7)
- [ ] PE Cant build (#14)
- [ ] PE Cant craft (#14)
- [ ] Crash on open inventory (#19)

**Comment by ZedCee** [comment]
I caught this:
- Command api appears to have changed.  Showing things like:
```
commands.help.header
commands.help.usage
commands.me.usage
commands.message.usage
commands.trigger.usage
commands.help.footer
```
Some past ones:
- Don't take any damage, from heights, water (still can lose air, that's client side), etc. Although occasionally die on login or respawn, sometimes receive fall damage in the initially seconds and continue receiving perpetual hits of damage
- No mob entities are visible

Some that are possibly user error:
- I cannot seem to build from b398931, `mvn package`fails.
- Other PE users cannot connect outside of my local network, this may be a configuration error on my part

DragonProxy Version: 0.0.5
Java JRE and JDK version: 8.2-2
Client version: 1.15.6 iOS
Server OS: Arch Linux

**Comment by TheDiamondYT1** [comment]
What directory do you package in

**Comment by ZedCee** [comment]
Following the wiki on compiling,
```
git clone https://github.com/DragonetMC/DragonProxy
cd DragonProxy/
cd proxy
mvn package
```
Fails with:

`[ERROR] Failed to execute goal on project proxy: Could not resolve dependencies for project org.dragonet.proxy:proxy:jar:0.0.6-preR1: Could not find artifact org.dragonet.proxy:protocol:jar:0.0.6-preR1 in sonatype (https://oss.sonatype.org/content/repositories/public/) -> [Help 1]`

**Comment by TheDiamondYT1** [comment]
Maybe try mvn install then mvn package after? Maybe try compiling in the root directory aswell.

**Comment by ZedCee** [comment]
`mvn install` and `mvn package` both fail the same way either directory.
There is a very long list of errors in the root directory.

**Comment by TheDiamondYT1** [comment]
Ik about those errors

**Comment by TheDiamondYT1** [comment]
Idk why it works for me from a freshly cloned repo

**Comment by TheDiamondYT1** [comment]
I dont have maven in PATH, so this is what i do:

**Comment by TheDiamondYT1** [comment]
1. Go to my Intellij IDEA installl directory
2. Go to i think plugins/maven/ or lib/plugins/maven or whatever, then copy the folder named maven3 to my fresh clone of DP repo 
3. I cd to proxy dir and move maven folder there
4. I type maven3\bin\mvn package

It works
