### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by lukeeey** [DragonetMC/DragonProxy#464]
This is a comprehensive TODO list that will be regularly updated. It contains what has been done and what needs to be done.

Last updated: 29/04/2020 at 15:16 pm

-------

### World
- [x] Chunks
- [ ] Biome colours
- [ ] Block entities
  - [ ] Chest (working on it)
  - [ ] Enderchest (working on it)
  - [x] Furnace
  - [x] Enchanting table
  - [x] Beacon
  - [x] Brewing stand
  - [x] Signs (kind of)
  - [ ] Spawner
  **...Plus more, but this is a good starting list**
- [ ] Implement sign editing
- [x] Sounds
- [x] Bossbar
- [x] Block breaking
- [x] Fix block breaking
- [ ] Support for enchantments and effects when breaking blocks
- [x] Block placing
- [x] Support for stopping time (`/gamerule doDaylightCycle false`)
- [ ] Dimension changing ([`feature/dimension-changing`](https://github.com/DragonetMC/DragonProxy/tree/feature/dimension-changing))
- [x] Implement maps
- [ ] Implement item frames (entities in java, block entity in bedrock. ugh.)
- [ ] World border support (#540)

### Player
- [x] Movement (slightly buggy)
- [x] Chat
  - [ ] Don't allow sending a message longer than 256 characters
- [x] Fix chat translation sometimes being weird (section symbol before a message, etc)
- [x] Full translation support
- [x] Fix movement on slabs/stairs/carpets
- [x] Commands (can also translate the arguments to bedrock! well, its a bit broken...)
- [ ] View statistics (/stats)
  - [x] General
  - [ ] Items
  - [ ] Mobs
- [ ] Inventory support
  - [x] Item NBT translation (name and lore currently)
  - [x] Dropping items
  - [ ] Moving items (untested)
  - [ ] Inventories ([`feature/inventories`](https://github.com/DragonetMC/DragonProxy/tree/feature/inventories))
    - [x] Player inventory
    - [ ] Beacon
    - [ ] Command block
    - [ ] Brewing stand
    - [ ] Furnace
    - [ ] Chest-style inventories (chest, ender chest etc)
      - [x] Block off rows that do not exist due to custom inventory sizes (Java can have an inventory with a single row, bedrock cant)
    - [ ] Enchanting table
    **...Plus more, but this is a good starting list**
- [x] Creative inventory
- [x] Don't allow creative crafting (doesn't exist in Java)
- [ ] Fix creative inventory being buggy
- [x] Block pick request
- [x] Fix player being invisible (#470)
- [x] Fix player flying (#484)

### Entities
- [x] Viewing other entities
- [x] Spawn egg support
- [x] Effects
- [ ] Full entity metadata support
  - [x] Pig
  - [x] Horse
  - [x] Creeper
  - [x] Wolf
  - [x] Ocelot
  - [ ] Fox
  - [x] Falling block
  - [x] Creeper
  - [x] Wither
  - [x] Cat
  - [x] Blaze
  - [x] Enderman
  - [x] Iron golem
  - [x] Snow golem
  - [x] Zombie
  - [x] Zombie villager
  - [x] Villager
  - [x] Ender dragon
- [x] Dropped items
- [x] Fishing rods
- [x] Giant zombies (because why not?)
- [ ] Riding entities (minecarts, boats etc) (being worked on)

### Other
- [x] Skin fetching
  - [x] Support for alex skins
- [x] Optifine cape support
- [x] Official Mojang cape support (and Minecon)
- [x] Mojang authentication (online mode)
- [ ] Scoreboard ([`feature/scoreboards-new`](https://github.com/DragonetMC/DragonProxy/tree/feature/scoreboards-new))
- [x] Titles
- [ ] Resource packs
- [x] Fix offline mode (see also #471)
- [ ] Multiple languages
- [x] Item pickup animation

**Comment by Kolya-Borisov** [comment]
Carpets also have the same issue as Slabs/Stairs where the players jump on each block.

**Comment by SoaresTI** [comment]
any forecast to run update 1.14.60?

**Comment by james090500** [comment]
> any forecast to run update 1.14.60?

Yes. Waiting for Libs to update

**Comment by Kolya-Borisov** [comment]
Snow, trapdoors, player heads, seapickles, lanterns, conduit, beds, campfires, brewing stands, and the stonecutter have the same issue as Slabs/Stairs/Carpets. Basically all halfblocks.

**Comment by Navoei** [comment]
Is there going to be support for viewing item enchantments?

**Comment by Ostrichbeta** [comment]
Foxes, lanterns, and other blocks'(mobs) lacking problems may cause the game crash. I tried to join a server that has a lot of lanterns and foxes, but the next second the game crashed, with plenty of error messages in the console.

**Comment by james090500** [comment]
Not always, I have a bunch of lanterns in my spawn and no crashes. But it's worth a go I guess

**Comment by lukeeey** [comment]
Sharing those error messages would help or I don’t know what the error is @Ostrichbeta

**Comment by Ostrichbeta** [comment]
> Sharing those error messages would help or I don’t know what the error is @Ostrichbeta 

I am so sorry, I made a mistake. I should post it on another similar project, not here. This one does not have this problem.

**Comment by lukeeey** [comment]
I’m guessing you mean geyser?

**Comment by Ostrichbeta** [comment]
> I’m guessing you mean geyser?

I made a silly mistake again, the problem happens when I use Dragon, it said 'Unhandled block entity', just like #514. The error message is:
`Unhandled block entity: minecraft:lectern`
It repeats over 200 times. The fox problem is nearly the same(just replace 'lectern' with 'fox'). Whenever I entered my account details in the dialog, the game crashed. (But the server only repeats the message above) But when I use Geyser I can join the remote server, but without the lectern appeared too. So I think that the problem comes from the algorithms. Maybe just 'skip' render them The problem will be fixed.

**Comment by lukeeey** [comment]
It's not to do with lecterns or foxes
